### ISSUE TITLE
Docker image has been disabled

### ISSUE THREAD

**Issue by MattMcL4475** [microsoft/gatk4-rnaseq-germline-snps-indels#4]
This image needs to be replaced in all tasks in the WDL; it has been deprecated by quay.io and can no longer be pulled: `quay.io/humancellatlas/secondary-analysis-star`

2024-05-11 07:44:10.811 info: Tes.Runner.Docker.DockerExecutor[0]
      Creating container with image name: quay.io/humancellatlas/secondary-analysis-star@sha256:7dc47321ddb6f26398ae2ac5d7576b5c1669adcec0a3d46025cad9a0747d6a59
2024-05-11 07:44:10.849 fail: Tes.Runner.Executor[0]
      Failed to execute container
      Docker.DotNet.DockerImageNotFoundException: Docker API responded with status code=NotFound, response={"message":"No such image: quay.io/humancellatlas/secondary-analysis-star@sha256:7dc47321ddb6f26398ae2ac5d7576b5c1669adcec0a3d46025cad9a0747d6a59"}
         at Docker.DotNet.ContainerOperations.<>c.<.cctor>b__30_1(HttpStatusCode statusCode, String responseBody)
         at Docker.DotNet.DockerClient.HandleIfErrorResponseAsync(HttpStatusCode statusCode, HttpResponseMessage response, IEnumerable`1 handlers)
         at Docker.DotNet.DockerClient.MakeRequestAsync(IEnumerable`1 errorHandlers, HttpMethod method, String path, IQueryString queryString, IRequestContent body, IDictionary`2 headers, TimeSpan timeout, CancellationToken token)
         at Docker.DotNet.ContainerOperations.CreateContainerAsync(CreateContainerParameters parameters, CancellationToken cancellationToken)
         at Tes.Runner.Docker.DockerExecutor.CreateContainerAsync(String imageName, String imageTag, List`1 commandsToExecute, List`1 volumeBindings, String workingDir)
         at Tes.Runner.Docker.DockerExecutor.RunOnContainerAsync(ExecutionOptions executionOptions)
         at Tes.Runner.Executor.ExecuteNodeContainerTaskAsync(DockerExecutor dockerExecutor)
2024-05-11 07:44:10.860 info: Tes.Runner.Events.EventsPublisher[0]
      Publishing event executorEnd to sink: BlobStorageEventSink
2024-05-11 07:44:10.874 fail: Tes.RunnerCLI.Commands.CommandHandlers[0]
      Failed to execute the task.
      Docker.DotNet.DockerImageNotFoundException: Docker API responded with status code=NotFound, response={"message":"No such image: quay.io/humancellatlas/secondary-analysis-star@sha256:7dc47321ddb6f26398ae2ac5d7576b5c1669adcec0a3d46025cad9a0747d6a59"}

C:\Users\mattmcl>docker pull quay.io/humancellatlas/secondary-analysis-star@sha256:7dc47321ddb6f26398ae2ac5d7576b5c1669adcec0a3d46025cad9a0747d6a59
quay.io/humancellatlas/secondary-analysis-star@sha256:7dc47321ddb6f26398ae2ac5d7576b5c1669adcec0a3d46025cad9a0747d6a59: Pulling from humancellatlas/secondary-analysis-star
[DEPRECATION NOTICE] Docker Image Format v1 and Docker Image manifest version 2, schema 1 support is disabled by default and will be removed in an upcoming release. Suggest the author of quay.io/humancellatlas/secondary-analysis-star@sha256:7dc47321ddb6f26398ae2ac5d7576b5c1669adcec0a3d46025cad9a0747d6a59 to upgrade the image to the OCI Format or Docker Image manifest v2, schema 2. More information at
https://docs.docker.com/go/deprecated-image-specs/

**Comment by MattMcL4475** [comment]
@vsmalladi are you able to fix this?  When this workflow is run, it fails, because the above image has been disabled by quay.io.  Can you possibly contact the author or find the new image and submit a PR to fix the WDL?

**Comment by BMurri** [comment]
I just looked. The tag that produced the above digest appears to be `v0.2.2-2.5.3a-40ead6e`, and these are the available tags for that image:

        "2.5.3a-1.0.0",
        "v0.2.2-2.5.3a-40ead6e",
        "v0.2.2-2.5.3a-1.0.0",
        "2.5.3a-40ead6e",
        "v2.7.8a",
        "v2.7.9a",
        "v2.7.9-1",
        "merge-star-outputs-v1.0.0",
        "merge-star-outputs-v1.1.0",
        "merge-star-outputs-v1.1.1",
        "merge-star-outputs-v1.1.2",
        "merge-star-outputs-v1.1.3",
        "merge-star-outputs-v1.1.4",
        "merge-star-outputs-v1.1.5",
        "merge-star-outputs-v1.1.6",
        "merge-star-outputs-v1.1.7",
        "merge-star-outputs-v1.1.8",
        "merge-star-outputs-v1.1.9"

**Comment by vsmalladi** [comment]
Let me see which one we can use.

**Comment by BMurri** [comment]
The following cannot be pulled (manifest type is not/no longer supported):

    "2.5.3a-1.0.0",
    "v0.2.2-2.5.3a-40ead6e",
    "v0.2.2-2.5.3a-1.0.0",
    "2.5.3a-40ead6e",

The following all appear to be accessible:
    "v2.7.8a",
    "v2.7.9a",
    "v2.7.9-1",
    "merge-star-outputs-v1.0.0",
    "merge-star-outputs-v1.1.0",
    "merge-star-outputs-v1.1.1",
    "merge-star-outputs-v1.1.2",
    "merge-star-outputs-v1.1.3",
    "merge-star-outputs-v1.1.4",
    "merge-star-outputs-v1.1.5",
    "merge-star-outputs-v1.1.6",
    "merge-star-outputs-v1.1.7",
    "merge-star-outputs-v1.1.8",
    "merge-star-outputs-v1.1.9",

**Comment by BMurri** [comment]
Interesting trivia: the four tags that fail are all signed (using a now completely obsolete manifest schema). The tags that succeed do not appear to be signed (but are all using a new enough manifest schema to appear to be pullable).

**Comment by vsmalladi** [comment]
We coud use:

https://github.com/broadinstitute/warp/blob/e5041b29d3c1992df44249a14a5b94b44b49ca4b/tasks/skylab/StarAlign.wdl#L9C22-L9C76

`"us.gcr.io/broad-gotc-prod/star:1.0.0-2.7.9a-1658781884"`
